// packages/renderer/src/app/views/SelectTaskView.tsx
import { usePomelloActions } from '@/app/context/PomelloContext';
import { useStore, useStoreActions } from '@/app/context/StoreContext';
import { useTranslate } from '@/shared/context/RuntimeContext';
import { useService } from '@/shared/context/ServiceContext';
import { Heading } from '@/ui/components/Heading';
import { SelectField } from '@/ui/components/SelectField';
import { createQuery } from '@tanstack/solid-query';
import { Component, Show, onMount } from 'solid-js';
import { unwrap } from 'solid-js/store';
import { Dynamic } from 'solid-js/web';
import { useTasksCacheKey } from '../hooks/useTasksCacheKey';

export const SelectTaskView: Component = () => {
  const { dialActionsSet, quickTaskReset } = useStoreActions();
  const { selectTask } = usePomelloActions();
  const getService = useService();
  const getTasksCacheKey = useTasksCacheKey();
  const store = useStore();
  const t = useTranslate();

  const tasks = createQuery(() => ({
    gcTime: Infinity,
    queryFn: getService().fetchTasks,
    queryKey: getTasksCacheKey(),
    throwOnError: true,
  }));

  onMount(() => {
    if (store.isQuickTaskSelectEnabled) {
      quickTaskReset();
    }
  });

  const handleTaskSelect = (id: string) => {
    const response = getService().onTaskSelect?.(id);

    if (response !== false) {
      selectTask(id);
    }
  };

  if (store.pomelloState.timer?.isActive) {
    dialActionsSet(['pauseTimer']);
  }

  const shouldOpenSelect = store.pomelloState.timer?.isActive ?? store.isQuickTaskSelectEnabled;

  return (
    <Show when={tasks.data}>
      {tasks => (
        <Show
          fallback={
            <>
              <Show when={getService().getSelectTaskHeading?.()}>
                {getSelectTaskHeading => <Heading>{getSelectTaskHeading()}</Heading>}
              </Show>
              <SelectField
                defaultOpen={shouldOpenSelect}
                items={unwrap(tasks())}
                noResultsMessage={t('noTasksFound')}
                onChange={handleTaskSelect}
                placeholder={t('selectTaskPlaceholder')}
              />
            </>
          }
          when={getService().SelectTaskView}
        >
          {getSelectTaskView => <Dynamic component={getSelectTaskView()} selectTask={selectTask} />}
        </Show>
      )}
    </Show>
  );
};

// packages/renderer/src/app/views/SelectTaskView.svelte
<script lang="ts">
  import { getErrorOverlayContext } from '@/app/contexts/errorOverlayContext';
  import { getPomelloActionsContext } from '@/app/contexts/pomelloActionsContext';
  import { getServiceContext } from '@/app/contexts/serviceContext';
  import getTasksCacheKey from '@/app/helpers/getTasksCacheKey';
  import getTranslator from '@/app/helpers/getTranslator';
  import Heading from '@/app/ui/Heading.svelte';
  import LoadingText from '@/app/ui/LoadingText.svelte';
  import SelectField from '@/app/ui/SelectField.svelte';
  import { createQuery } from '@tanstack/svelte-query';
  import { onMount } from 'svelte';

  export let quickTaskMode: boolean;
  export let resetQuickTaskMode: () => void;

  const { fetchTasks, getSelectTaskHeading, onTaskSelect, SelectTaskView } = getServiceContext();
  const pomelloActions = getPomelloActionsContext();
  const setErrorOverlay = getErrorOverlayContext();
  const tasksCacheKey = getTasksCacheKey();
  const translate = getTranslator();

  $: tasks = createQuery({
    cacheTime: Infinity,
    onError: error => {
      setErrorOverlay({
        heading: translate('errorHeading'),
        message: translate('fetchTasksErrorMessage'),
        error,
        retryAction: {
          label: translate('errorRetry'),
          onClick: $tasks.refetch,
        },
      });
    },
    queryFn: fetchTasks,
    queryKey: $tasksCacheKey,
  });

  const initialQuickTaskMode = quickTaskMode;

  onMount(() => {
    resetQuickTaskMode();
  });

  const handleTaskSelect = (event: CustomEvent<string>) => {
    selectTask(event.detail);
  };

  const selectTask = (id: string) => {
    const response = onTaskSelect?.(id);

    if (response !== false) {
      pomelloActions.selectTask(id);
    }
  };

  // TODO: Add pause dial action when timer is active
  // TODO: Replace query key
</script>

{#if SelectTaskView}
  <svelte:component
    this={SelectTaskView.component}
    {...SelectTaskView.additionalProps}
    {selectTask}
  />
{:else if $tasks.isSuccess}
  {#if getSelectTaskHeading}
    <Heading>{getSelectTaskHeading()}</Heading>
  {/if}
  <SelectField
    defaultOpen={initialQuickTaskMode}
    items={$tasks.data}
    noResultsMessage={translate('noTasksFound')}
    on:change={handleTaskSelect}
    placeholder={translate('selectTaskPlaceholder')}
  />
{:else if $tasks.isFetching}
  <LoadingText />
{/if}
