// packages/renderer/src/ui/app/SelectField/SelectField.tsx
import { useTranslate } from '@/shared/context/RuntimeContext';
import { SelectItem } from '@pomello-desktop/domain';
import { Component, createEffect, onCleanup } from 'solid-js';
import styles from './SelectField.module.scss';

type SelectFieldProps = {
  defaultOpen?: boolean;
  items: SelectItem[];
  noResultsMessage?: string;
  onChange(optionId: string): void;
  placeholder?: string;
};

export const SelectField: Component<SelectFieldProps> = props => {
  const t = useTranslate();

  let buttonRef: HTMLButtonElement;

  createEffect(() => {
    window.app.setSelectItems({
      items: props.items,
      noResultsMessage: props.noResultsMessage,
      placeholder: getPlaceholder(),
    });
  });

  createEffect(() => {
    const unsubscribe = window.app.onSelectChange(props.onChange);

    onCleanup(unsubscribe);
  });

  const getPlaceholder = () => props.placeholder ?? t('selectPlaceholder');

  const showSelectWindow = () => {
    const bounds = buttonRef.getBoundingClientRect();

    window.app.showSelect({
      buttonBounds: {
        height: bounds.height,
        width: bounds.width,
        x: bounds.x,
        y: bounds.y,
      },
    });
  };

  const handleButtonClick = () => {
    showSelectWindow();
  };

  const handleKeyDown = (event: KeyboardEvent) => {
    if (event.code === 'Space' && event.target === document.body) {
      showSelectWindow();
    }
  };

  document.addEventListener('keydown', handleKeyDown);

  onCleanup(() => {
    document.removeEventListener('keydown', handleKeyDown);

    window.app.resetSelect();
  });

  // This is much simpler than doing a lot of message passing to figure out if
  // the select window has updated.
  if (props.defaultOpen) {
    setTimeout(showSelectWindow, 5);
  }

  return (
    <button class={styles.button} onClick={handleButtonClick} ref={buttonRef!}>
      {getPlaceholder()}
    </button>
  );
};

// packages/renderer/src/app/ui/SelectField/SelectField.svelte
<script lang="ts">
  import getTranslator from '@/app/getTranslator';
  import type { SelectItem } from '@domain';
  import { createEventDispatcher, onMount } from 'svelte';

  let customPlaceholder: string | undefined = undefined;
  export let defaultOpen = false;
  export let items: SelectItem[];
  export let noResultsMessage: string | undefined = undefined;
  export { customPlaceholder as placeholder };

  const dispatch = createEventDispatcher<{ change: string }>();
  const translate = getTranslator();

  let buttonElement: HTMLButtonElement | undefined = undefined;
  let shouldOpenOnUpdate = defaultOpen;

  $: placeholder = customPlaceholder ?? $translate('selectPlaceholder');

  $: {
    window.app.setSelectItems({ items, noResultsMessage, placeholder });

    // This is much simpler than doing a lot of message passing to figure out if
    // the select window has updated.
    if (shouldOpenOnUpdate) {
      setTimeout(showSelectWindow, 5);
    }

    shouldOpenOnUpdate = false;
  }

  onMount(() => {
    const onSelectChangeUnsubscribe = window.app.onSelectChange(optionId => {
      dispatch('change', optionId);
    });

    return () => {
      onSelectChangeUnsubscribe();
      window.app.resetSelect();
    };
  });

  const handleDocumentKeyDown = (event: KeyboardEvent) => {
    if (event.code === 'Space' && event.target === document.body) {
      showSelectWindow();
    }
  };

  const handleButtonClick = () => {
    showSelectWindow();
  };

  const showSelectWindow = () => {
    if (buttonElement) {
      const bounds = buttonElement.getBoundingClientRect();

      window.app.showSelect({
        buttonBounds: {
          height: bounds.height,
          width: bounds.width,
          x: bounds.x,
          y: bounds.y,
        },
      });
    }
  };
</script>

<svelte:document on:keydown={handleDocumentKeyDown} />

<button bind:this={buttonElement} class="button" on:click={handleButtonClick}>
  {placeholder}
</button>

<style lang="scss">
  $button-padding: 2px;

  .button {
    position: relative;
    padding: 0 $button-padding;
    border: 0;
    margin-left: -$button-padding;
    background-color: transparent;
    color: inherit;

    &::after {
      position: absolute;
      bottom: 0;
      display: block;
      width: calc(100% - ($button-padding * 2));
      border-bottom: 1px dotted var(--app-content-default);
      content: '';
      opacity: 0;
      transition: opacity 140ms ease-in-out;
    }

    &:hover {
      cursor: pointer;

      &::after {
        opacity: 0.8;
      }
    }
  }
</style>
