// packages/renderer/src/app/views/TaskView.tsx
import { useService } from '@/shared/context/ServiceContext';
import { Heading } from '@/ui/app/Heading';
import { Text } from '@/ui/app/Text';
import { Component, Show } from 'solid-js';
import { useStoreActions } from '../context/StoreContext';
import { useCurrentTask } from '../hooks/useCurrentTask';

export const TaskView: Component = () => {
  const { dialActionsSet } = useStoreActions();
  const getService = useService();

  const currentTask = useCurrentTask();

  dialActionsSet(['pauseTimer', 'addNote', 'switchTask', 'voidTask', 'completeTask']);

  return (
    <>
      <Show when={getService().getTaskHeading?.()}>
        {getTaskHeading => <Heading>{getTaskHeading()}</Heading>}
      </Show>
      <Text>{currentTask().label}</Text>
    </>
  );
};

// packages/renderer/src/app/views/TaskView/TaskView.tsx
import { dialActionsSet, dialActionsUnset } from '@/app/appSlice';
import useCurrentTask from '@/app/hooks/useCurrentTask';
import Heading from '@/app/ui/Heading';
import Text from '@/app/ui/Text';
import useService from '@/shared/hooks/useService';
import { FC, useEffect } from 'react';
import { useDispatch } from 'react-redux';

const TaskView: FC = () => {
  const dispatch = useDispatch();
  const { getTaskHeading } = useService();

  const { currentTaskLabel } = useCurrentTask();

  useEffect(() => {
    dispatch(dialActionsSet(['pauseTimer', 'addNote', 'switchTask', 'voidTask', 'completeTask']));

    return () => {
      dispatch(dialActionsUnset());
    };
  }, [dispatch]);

  return (
    <>
      {getTaskHeading && <Heading>{getTaskHeading()}</Heading>}
      <Text>{currentTaskLabel}</Text>
    </>
  );
};

export default TaskView;
