// packages/renderer/src/app/ui/Content/Content.tsx
import cc from 'classcat';
import { FC, ReactNode } from 'react';
import styles from './Content.module.scss';

interface ContentProps {
  children: ReactNode;
  className?: string;
}

const Content: FC<ContentProps> = ({ children, className }) => {
  return <div className={cc([styles.content, className])}>{children}</div>;
};

export default Content;

// packages/renderer/src/ui/app/Content/Content.tsx
import cc from 'classcat';
import { ParentComponent } from 'solid-js';
import styles from './Content.module.scss';

type ContentProps = {
  class?: string;
};

export const Content: ParentComponent<ContentProps> = props => {
  return <div class={cc([styles.content, props.class])}>{props.children}</div>;
};
