// packages/renderer/src/app/components/Layout/Layout.tsx
import { selectPomelloState } from '@/app/appSlice';
import useHotkeys from '@/app/hooks/useHotkeys';
import usePomelloActions from '@/app/hooks/usePomelloActions';
import useTranslation from '@/shared/hooks/useTranslation';
import cc from 'classcat';
import { FC, ReactNode, useCallback, useEffect, useRef, useState } from 'react';
import { ErrorBoundary } from 'react-error-boundary';
import { useSelector } from 'react-redux';
import Dial from '../Dial';
import Overtime from '../Overtime';
import { ReactComponent as MenuIcon } from './assets/menu.svg';
import selectShowCancelTaskDialog from './helpers/selectShowCancelTaskDialog';
import styles from './Layout.module.scss';
import Menu from './Menu';

interface LayoutProps {
  children: ReactNode;
  onTaskCreate(): void;
}

const Layout: FC<LayoutProps> = ({ children, onTaskCreate }) => {
  const { t } = useTranslation();
  const { getHotkeyLabel, registerHotkeys } = useHotkeys();

  const { reset } = usePomelloActions();
  const { timer, overtime } = useSelector(selectPomelloState);
  const showCancelTaskDialog = useSelector(selectShowCancelTaskDialog);

  const menuRef = useRef<HTMLElement>(null);
  const [menuOffset, setMenuOffset] = useState(0);
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const createTask = useCallback(() => {
    onTaskCreate();
    setIsMenuOpen(false);
  }, [onTaskCreate]);

  const routeHome = useCallback(async () => {
    if (showCancelTaskDialog) {
      const { response } = await window.app.showMessageBox({
        buttons: [t('cancelTaskDialogConfirm'), t('cancelTaskDialogCancel')],
        cancelId: 1,
        defaultId: 0,
        detail: t('cancelTaskDialogMessage'),
        message: t('cancelTaskDialogHeading'),
        title: 'Pomello',
        type: 'warning',
      });

      if (response === 1) {
        return;
      }
    }

    reset();
    setIsMenuOpen(false);
  }, [reset, showCancelTaskDialog, t]);

  useEffect(() => {
    return registerHotkeys({
      createTask,
      routeHome,
      toggleMenu,
    });
  }, [createTask, registerHotkeys, routeHome]);

  const handleMenuClick = () => {
    toggleMenu();
  };

  const handleCreateTaskClick = () => {
    createTask();
  };

  const handleHomeButtonClick = () => {
    routeHome();
  };

  const toggleMenu = () => {
    if (menuRef.current) {
      setMenuOffset(menuRef.current.getBoundingClientRect().width);
    }

    setIsMenuOpen(prevIsMenuOpen => !prevIsMenuOpen);
  };

  const menuTranslationKey = isMenuOpen ? 'closeMenu' : 'openMenu';

  return (
    <>
      <Menu
        isOpen={isMenuOpen}
        onCreateTaskClick={handleCreateTaskClick}
        onHomeClick={handleHomeButtonClick}
        ref={menuRef}
      />
      <main
        className={cc({
          [styles.container]: true,
          [styles.menuOpen]: isMenuOpen,
        })}
        data-mode={timer?.isActive ? timer.type : undefined}
        style={{
          transform: isMenuOpen && menuOffset ? `translate(${menuOffset}px)` : undefined,
        }}
      >
        <button
          aria-label={t(`${menuTranslationKey}Label`)}
          className={styles.menuButton}
          onClick={handleMenuClick}
          title={t(`${menuTranslationKey}Title`, { hotkey: getHotkeyLabel('toggleMenu') })}
        >
          <MenuIcon aria-hidden width={4} />
        </button>
        <ErrorBoundary fallback={<>TODO: Error handler</>}>
          <div className={styles.content}>{children}</div>
          {(timer || overtime) && (
            <div className={styles.timers}>
              {overtime && <Overtime isDialVisible={Boolean(timer)} overtime={overtime} />}
              {timer && <Dial key={timer.type} timer={timer} />}
            </div>
          )}
        </ErrorBoundary>
      </main>
    </>
  );
};

export default Layout;

// packages/renderer/src/app/components/Layout/Layout.svelte
<script lang="ts">
  import { getPomelloActionsContext } from '@/app/contexts/pomelloActionsContext';
  import { getPomelloStateContext } from '@/app/contexts/pomelloStateContext';
  import getCommandFormatter from '@/app/helpers/getCommandFormatter';
  import getTranslator from '@/app/helpers/getTranslator';
  import registerHotkeys from '@/app/helpers/registerHotkeys';
  import { getSettingsContext } from '@/shared/contexts/settingsContext';
  import { derived } from 'svelte/store';
  import Menu from './Menu.svelte';
  import MenuIcon from './assets/menu.svg?component';

  const { reset } = getPomelloActionsContext();
  const pomelloState = getPomelloStateContext();
  const settings = getSettingsContext();
  const translate = getTranslator();

  const appMode = derived(pomelloState, $pomelloState => $pomelloState.status);
  const formatCommand = getCommandFormatter($translate);

  let isMenuOpen = false;
  let menuElement: HTMLElement | undefined = undefined;
  let menuOffset: number = 0;

  $: menuTranslationKey = isMenuOpen ? 'closeMenuLabel' : 'openMenuLabel';

  const handleCreateTaskClick = () => {
    // TODO: Add create task
  };

  const handleMenuClick = () => {
    toggleMenu();
  };

  const handleHomeButtonClick = () => {
    routeHome();
  };

  const routeHome = async () => {
    const showCancelTaskDialog =
      $settings.warnBeforeTaskCancel &&
      $pomelloState.timer?.isActive &&
      $pomelloState.timer.type === 'TASK';

    if (showCancelTaskDialog) {
      const { response } = await window.app.showMessageBox({
        buttons: [$translate('cancelTaskDialogConfirm'), $translate('cancelTaskDialogCancel')],
        cancelId: 1,
        defaultId: 0,
        detail: $translate('cancelTaskDialogMessage'),
        message: $translate('cancelTaskDialogHeading'),
        title: 'Pomello',
        type: 'warning',
      });

      if (response === 1) {
        return;
      }
    }

    reset();

    isMenuOpen = false;
  };

  const toggleMenu = () => {
    if (menuElement) {
      menuOffset = menuElement.getBoundingClientRect().width;
    }

    isMenuOpen = !isMenuOpen;
  };

  registerHotkeys({
    toggleMenu,
    routeHome,
  });
</script>

<Menu
  bind:menuElement
  isOpen={isMenuOpen}
  on:createTask={handleCreateTaskClick}
  on:home={handleHomeButtonClick}
/>
<main
  class="container"
  data-mode={$appMode}
  style:transform={isMenuOpen && menuOffset ? `translate(${menuOffset}px)` : undefined}
>
  <button
    aria-label={$translate(menuTranslationKey)}
    class="menuButton"
    on:click={handleMenuClick}
    title={formatCommand('openMenuLabel', 'toggleMenu')}
  >
    <MenuIcon aria-hidden width={4} />
  </button>
  <div class="content">
    <slot />
  </div>
</main>

<style lang="scss">
  @import '../../../shared/styles/shared.scss';

  :global(body) {
    overflow: hidden;
    -webkit-app-region: drag;
    background-color: var(--menu-background);
  }

  :global(button) {
    -webkit-app-region: no-drag;
  }

  .container {
    position: relative;
    display: flex;
    align-items: center;
    background: var(--app-background-default);
    color: var(--app-content-default);
    transition: transform 500ms $ease-out-circ;
    user-select: none;

    &[data-mode='TASK'] {
      background-color: var(--app-background-task);
      color: var(--app-content-task);
    }

    &[data-mode='SHORT_BREAK'] {
      background-color: var(--app-background-short-break);
      color: var(--app-content-short-break);
    }

    &[data-mode='LONG_BREAK'] {
      background-color: var(--app-background-long-break);
      color: var(--app-content-long-break);
    }
  }

  .menuButton {
    @extend %clickable;

    display: flex;
    width: 16px;
    height: 100vh;
    flex-shrink: 0;
    align-items: center;
    justify-content: center;
    padding: 0;
    border: 0;
    background-color: var(--app-button-background-default);
    color: var(--menu-toggle-content-default);

    &:hover,
    &:focus {
      background-color: var(--app-button-background-hover);
      color: var(--menu-toggle-content-hover);
    }
  }

  .content {
    position: relative;
    overflow: hidden;
    height: 100vh;
    flex: 1;
  }
</style>
