// packages/renderer/src/app/components/Layout/Menu.svelte
<script lang="ts">
  import getTranslator from '@/app/getTranslator';
  import { createEventDispatcher } from 'svelte';
  import AddIcon from './assets/add.svg?component';
  import CogIcon from './assets/cog.svg?component';
  import HomeIcon from './assets/home.svg?component';

  export let menuElement: HTMLElement | undefined = undefined;
  export let isOpen: boolean;

  const dispatch = createEventDispatcher<{
    createTask: void;
    home: void;
  }>();

  const translate = getTranslator();

  const handleHomeClick = () => {
    dispatch('home');
  };

  const handleCreateTaskClick = () => {
    dispatch('createTask');
  };
</script>

<nav aria-label={$translate('menuLabel')} bind:this={menuElement} class="menu">
  <button
    aria-hidden={!isOpen}
    aria-label={$translate('homeButtonLabel')}
    class="button"
    on:click={handleHomeClick}
    tabIndex={isOpen ? 0 : -1}
  >
    <HomeIcon aria-hidden />
  </button>
  <button
    aria-label={$translate('dashboardButtonLabel')}
    aria-hidden={!isOpen}
    class="button"
    tabIndex={isOpen ? 0 : -1}
  >
    <CogIcon aria-hidden />
  </button>
  <button
    aria-hidden={!isOpen}
    aria-label={$translate('createTaskButtonLabel')}
    class="button"
    on:click={handleCreateTaskClick}
    tabIndex={isOpen ? 0 : -1}
  >
    <AddIcon aria-hidden />
  </button>
</nav>

<style lang="scss">
  .menu {
    position: absolute;
    display: flex;
    height: 100%;
    align-items: center;
    padding: 0 8px;
  }

  .button {
    display: flex;
    width: 36px;
    height: 36px;
    align-items: center;
    justify-content: center;
    border: 0;
    border-radius: 50%;
    background-color: var(--menu-button-background-default);
    color: var(--menu-button-content-default);

    &:hover,
    &:focus {
      background-color: var(--menu-button-background-hover);
      color: var(--menu-button-content-hover);
    }

    :global(svg) {
      width: 20px;
    }
  }
</style>

// packages/renderer/src/app/components/Layout/Menu.tsx
import useTranslation from '@/shared/hooks/useTranslation';
import { forwardRef } from 'react';
import { ReactComponent as AddIcon } from './assets/add.svg';
import { ReactComponent as CogIcon } from './assets/cog.svg';
import { ReactComponent as HomeIcon } from './assets/home.svg';
import styles from './Menu.module.scss';

interface MenuProps {
  isOpen: boolean;
}

const Menu = forwardRef<HTMLElement, MenuProps>(({ isOpen }, ref) => {
  const { t } = useTranslation();

  return (
    <nav aria-label={t('menuLabel')} className={styles.menu} ref={ref}>
      <button
        aria-label={t('homeButtonLabel')}
        aria-hidden={!isOpen}
        className={styles.button}
        tabIndex={isOpen ? 0 : -1}
      >
        <HomeIcon aria-hidden />
      </button>
      <button
        aria-label={t('dashboardButtonLabel')}
        aria-hidden={!isOpen}
        className={styles.button}
        tabIndex={isOpen ? 0 : -1}
      >
        <CogIcon aria-hidden />
      </button>
      <button
        aria-label={t('createTaskButtonLabel')}
        aria-hidden={!isOpen}
        className={styles.button}
        tabIndex={isOpen ? 0 : -1}
      >
        <AddIcon aria-hidden />
      </button>
    </nav>
  );
});

export default Menu;
