// packages/renderer/src/app/components/Routes.svelte
<script lang="ts">
  import { getPomelloActionsContext } from '@/app/contexts/pomelloActionsContext';
  import { getPomelloStateContext } from '@/app/contexts/pomelloStateContext';
  import { getServiceContext } from '@/app/contexts/serviceContext';
  import SelectTaskView from '@/app/views/SelectTaskView.svelte';
  import TaskView from '@/app/views/TaskView.svelte';
  import { derived } from 'svelte/store';

  const { setReady } = getPomelloActionsContext();
  const pomelloState = getPomelloStateContext();
  const service = getServiceContext();
  const status = derived(pomelloState, $pomelloState => $pomelloState.status);

  let quickTaskMode = false;

  const handleServiceReady = (options: { openTaskSelect?: boolean } = {}) => {
    if (options.openTaskSelect) {
      quickTaskMode = true;
    }

    setReady();
  };

  const resetQuickTaskMode = () => {
    quickTaskMode = false;
  };
</script>

{#if $status === 'INITIALIZING'}
  {#if service.InitializingView}
    <svelte:component
      this={service.InitializingView.component}
      {...service.InitializingView.additionalProps}
      onReady={handleServiceReady}
    />
  {:else}
    {setReady()}
  {/if}
{:else if $status === 'SELECT_TASK'}
  <SelectTaskView {quickTaskMode} {resetQuickTaskMode} />
{:else if $status === 'TASK'}
  <TaskView />
{/if}

// packages/renderer/src/app/components/Routes/Routes.tsx
import { quickTaskSelectEnabled, selectPomelloStatus } from '@/app/appSlice';
import usePomelloActions from '@/app/hooks/usePomelloActions';
import BreakView from '@/app/views/BreakView';
import CreatePomelloAccountView from '@/app/views/CreatePomelloAccountView';
import SelectTaskView from '@/app/views/SelectTaskView';
import TaskCompleteView from '@/app/views/TaskCompleteView';
import TaskTimerEndView from '@/app/views/TaskTimerEndView';
import TaskView from '@/app/views/TaskView';
import TaskVoidView from '@/app/views/TaskVoidView';
import { usePomelloConfigSelector } from '@/shared/hooks/usePomelloConfig';
import useService from '@/shared/hooks/useService';
import { FC, useCallback } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import selectPromptCreatePomelloAccount from './selectPromptCreatePomelloAccount';
import useTrackStats from './useTrackStats';

const Routes: FC = () => {
  const dispatch = useDispatch();
  const service = useService();

  useTrackStats();

  const { setReady } = usePomelloActions();

  const promptCreatePomelloAccount = usePomelloConfigSelector(selectPromptCreatePomelloAccount);

  const status = useSelector(selectPomelloStatus);

  const handleServiceReady = useCallback(
    (options: { openTaskSelect?: boolean } = {}) => {
      if (options.openTaskSelect) {
        dispatch(quickTaskSelectEnabled());
      }

      setReady();
    },
    [dispatch, setReady]
  );

  if (status === 'INITIALIZING') {
    if (service.InitializingView) {
      return <service.InitializingView onReady={handleServiceReady} />;
    } else {
      setReady();
      return null;
    }
  }

  if (promptCreatePomelloAccount) {
    return <CreatePomelloAccountView />;
  }

  if (status === 'SELECT_TASK') {
    return <SelectTaskView />;
  }

  if (status === 'TASK') {
    return <TaskView />;
  }

  if (status === 'TASK_TIMER_END_PROMPT') {
    return <TaskTimerEndView />;
  }

  if (status === 'TASK_COMPLETE_PROMPT') {
    return <TaskCompleteView />;
  }

  if (status === 'TASK_VOID_PROMPT') {
    return <TaskVoidView />;
  }

  if (status === 'SHORT_BREAK' || status === 'LONG_BREAK') {
    return <BreakView type={status} />;
  }

  return null;
};

export default Routes;
