// packages/renderer/src/ui/components/ButtonsOverlay/ButtonsOverlay.tsx
import { For, JSX, ParentComponent } from 'solid-js';
import { Content } from '../Content/Content';
import styles from './ButtonsOverlay.module.scss';

interface ButtonsOverlayProps {
  buttons: Button[];
}

interface Button {
  content: JSX.Element;
  onClick(): void;
  title?: string;
}

export const ButtonsOverlay: ParentComponent<ButtonsOverlayProps> = props => {
  return (
    <div class={styles.buttonsOverlay}>
      <Content class={styles.content}>{props.children}</Content>
      <div class={styles.buttons}>
        <For each={props.buttons}>
          {button => (
            <button onClick={button.onClick} title={button.title}>
              {button.content}
            </button>
          )}
        </For>
      </div>
    </div>
  );
};

// packages/renderer/src/app/ui/ButtonsOverlay/ButtonsOverlay.tsx
import { FC, ReactNode } from 'react';
import Content from '../Content';
import styles from './ButtonsOverlay.module.scss';

interface ButtonsOverlayProps {
  buttons: Button[];
  children?: ReactNode;
}

interface Button {
  content: ReactNode;
  id: string;
  onClick(): void;
  title?: string;
}

const ButtonsOverlay: FC<ButtonsOverlayProps> = ({ buttons, children }) => {
  return (
    <div className={styles.buttonsOverlay}>
      <Content className={styles.content}>{children}</Content>
      <div className={styles.buttons}>
        {buttons.map(button => (
          <button key={button.id} onClick={button.onClick} title={button.title}>
            {button.content}
          </button>
        ))}
      </div>
    </div>
  );
};

export default ButtonsOverlay;
